### ISSUE TITLE
add new protocol

### ISSUE THREAD

**Issue by Herojhjh** [CookieSoftware/TSP#45]
add mcpe/protocl please

**Comment by wiligangster** [comment]
Why ?

**Comment by MasterOfTheRealm** [comment]
Is it because some updated plugins depend on network\mcpe\protocol\ProtocolInfo ?

**Comment by Herojhjh** [comment]
y

**Comment by BrianZP** [comment]
Well. It is true that new and updated plugins use 
pocketmine/network/mcpe/protocol now instead of
pocketmine/network/protocol but to integrate that change requires a lot of changes in a lot of files which is completely a pain in the butt and further a little unnecessary. So what I reckon is to just change the path for the plugin to search by editing their Main.php and problem is solved.
